TEAM_ABBRS = {
    'Atlanta Falcons'       : 'ATL',
    'Philadelphia Eagles'   : 'PHI',
    'Tampa Bay Buccaneers'  : 'TB',
    'New Orleans Saints'    : 'NO',
    'Cincinnati Bengals'    : 'CIN',
    'Indianapolis Colts'    : 'IND',
    'Buffalo Bills'         : 'BUF',
    'Baltimore Ravens'      : 'BAL',
    'Tennessee Titans'      : 'TEN',
    'Miami Dolphins'        : 'MIA',
    'Pittsburgh Steelers'   : 'PIT',
    'Cleveland Browns'      : 'CLE',
    'Houston Texans'        : 'HOU',
    'New England Patriots'  : 'NE',
    'San Francisco 49ers'   : 'SF',
    'Minnesota Vikings'     : 'MIN',
    'Jacksonville Jaguars'  : 'JAX',
    'New York Giants'       : 'NYG',
    'Kansas City Chiefs'    : 'KC',
    'Los Angeles Chargers'  : 'LAC',
    'Seattle Seahawks'      : 'SEA',
    'Denver Broncos'        : 'DEN',
    'Dallas Cowboys'        : 'DAL',
    'Carolina Panthers'     : 'CAR',
    'Washington Redskins'   : 'WAS',
    'Washington Commanders' : 'WAS',
    'Washington Football Team':'WAS',
    'Arizona Cardinals'     : 'ARI',
    'Chicago Bears'         : 'CHI',
    'Green Bay Packers'     : 'GB',
    'New York Jets'         : 'NYJ',
    'Detroit Lions'         : 'DET',
    'Los Angeles Rams'      : 'LAR',
    'Oakland Raiders'       : 'OAK',
    'Las Vegas Raiders'     : 'LV'
}


BDB_TEAM_ABBRS = {
    'ATL': 'ATL',
    'PHI': 'PHI',
    'TAM': 'TB',
    'NOR': 'NO',
    'CIN': 'CIN',
    'IND': 'IND',
    'BUF': 'BUF',
    'BAL': 'BAL',
    'TEN': 'TEN',
    'MIA': 'MIA',
    'PIT': 'PIT',
    'CLE': 'CLE',
    'HOU': 'HOU',
    'NWE': 'NE',
    'SFO': 'SF',
    'MIN': 'MIN',
    'JAX': 'JAX',
    'NYG': 'NYG',
    'KAN': 'KC',
    'LAC': 'LAC',
    'SEA': 'SEA',
    'DEN': 'DEN',
    'DAL': 'DAL',
    'CAR': 'CAR',
    'WAS': 'WAS',
    'ARI': 'ARI',
    'CHI': 'CHI',
    'GNB': 'GB',
    'NYJ': 'NYJ',
    'DET': 'DET',
    'LAR': 'LAR',
    'OAK': 'OAK',
    'LVR': 'LV'
}